version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    env_file:
     - ../.env
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: mysql
            host: mysql
            database: db-graphql 
            user: root
            password: Revrcp1984
            rawAccess: false
            port: 3306
            migrations: true
  mysql:
    image: mysql:5.7
    restart: always
    # Uncomment the next two lines to connect to your your database from outside the Docker environment, e.g. using a database GUI like Workbench
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Revrcp1984
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
